### ISSUE TITLE
Bridge LAN adding devices

### ISSUE THREAD

**Issue by muezalmanna** [beckyricha/Broadlink-RM-SmartThings-Alexa#10]
using the rm bridge LAN , is there any way to add my devices to smartthings account without having a hub? , the bridge, the codes, the handler are fine but i dont have any hub in my location

**Comment by beckyricha** [comment]
If you don't want to use a hub, use the cloud version. It doesn't need a hub. The LAN version is designed to pass the commands through a hub on your LAN. I have not been updating they one, so please advise if it gives you any issues and i can try to correct them.
Becky
On Jan 3, 2017 10:58 AM, muezalmanna <notifications@github.com> wrote:using the rm bridge LAN , is there any way to add my devices to smartthings account without having a hub? , the bridge, the codes, the handler are fine but i dont have any hub in my location

**Comment by muezalmanna** [comment]
Thanks for the support Becky
i did what you told me and after 3 hours of resetting and configuring i got alexa to discover the devices i created, but it doesn't send any signal to my rm pro. 
(the dynamic dns is fine, the eControl app works fine, the bridge is on and the ip & port are set static, the codes are learned & named in the rm bridge portal "Tv on","Tv off" & works fine, i added the device handler in smartthings and entered my ddns link and port as shown in the readme file, finally i created the device and alexa discovered it) Yet i don't see the orange blink in the rm pro when i as alexa to turn on and off.

**Comment by beckyricha** [comment]
Hi. Sorry it sounds like this had been a painful process for you. It's hard to troubleshoot this one remotely, but I'll give it a shot. What happens when you try to control the devices from your smart things app? 

On Jan 4, 2017 1:05 PM, muezalmanna <notifications@github.com> wrote:Thanks for the support Becky
i did what you told me and after 3 hours of resetting and configuring i got alexa to discover the devices i created, but it doesn't send any signal to my rm pro.
(the dynamic dns is fine, the eControl app works fine, the bridge is on and the ip & port are set static, the codes are learned & named in the rm bridge portal "Tv on","Tv off" & works fine, i added the device handler in smartthings and entered my ddns link and port as shown in the readme file, finally i created the device and alexa discovered it) Yet i don't see the orange blink in the rm pro when i as alexa to turn on and off.

**Comment by beckyricha** [comment]
Also, when you set up the rm bridge and choose a port, did you also forward that port to the Android device on your router?  

I'll also take another look back at those cloud based instructions when i get home tonight and make sure everything I've learned through using the LAN version since initial publication is reflected there but as well.

**Comment by muezalmanna** [comment]
When alexa send the signal to smartthing to turn on the device but it seems like smartthings can't access the rm, either the router or the bridge isn't connected properly 
,,,, I did forward the port to the android static ip from the router settings

**Comment by beckyricha** [comment]
When you use the smart thing app without Alexa, can that control it?
On Jan 4, 2017 1:36 PM, muezalmanna <notifications@github.com> wrote:When alexa send the signal to smartthing to turn on the device but it seems like smartthings can't access the rm, either the router or the bridge isn't connected properly
,,,, I did forward the port to the android static ip from the router settings

**Comment by muezalmanna** [comment]
I just tried the smartthings app it didn't control it

**Comment by beckyricha** [comment]
Then i will need to take another look at the code and make sure it's OK. I'll get back to you in a few hours.
On Jan 4, 2017 4:13 PM, muezalmanna <notifications@github.com> wrote:I just tried the smartthings app it didn't control it

**Comment by beckyricha** [comment]
I tried the code as posted and it didn't work for me either, but I found and corrected a bug so that it does.  Try the new device handler code, or just change line 45 in your already inserted version.  Where it reads "device.displayName" that should just be device.name.  I also had issues at first because I used the LAN instructions instead of cloud ones.  Make sure your uri is in the format "http://username:password@your.ip.address:yourport" or, if you have not entered security info, just http://your.ip.address:yourport.  Once I got those right, mine worked fine.  Sorry about that, and thanks for helping to find this, even if the unfortunate and hard way :)  Please let me know whether this resolves your issue.  

Becky

**Comment by muezalmanna** [comment]
Yessssss it worked finally,
Alexa and smartthings could  send commands to rm pro now, even tho the TV didn't turn on, the signal was sent fine.
Later after work I'll learn the codes again and create other devices, it shall work
Thank you Becky you were great help

**Comment by beckyricha** [comment]
Sorry it was about a bug. I'm glad it works.
On Jan 4, 2017 11:00 PM, muezalmanna <notifications@github.com> wrote:Yessssss it worked finally,
Alexa and smartthings could  send commands to rm pro now, even tho the TV didn't turn on, the signal was sent fine.
Later after work I'll learn the codes again and create other devices, it shall work
Thank you Becky you were great help
