### ISSUE TITLE
Cannot connect smartthings to RM bridge

### ISSUE THREAD

**Issue by hapahopa** [beckyricha/Broadlink-RM-SmartThings-Alexa#11]
Hi there,

First of all, thank you so much for putting the codes/files here so that other people can use it for free. 

Just a quick introduction, I have a Boradlink RM that I control my blinds with, I have a google home that I want to control my Broadlink with !

I've installed the RM Bridge on an android device already and got the 192.168 urls that could control my blinds if I'm on a local network (same subnet)

I also bought a Samsung smart things to use it as a hub and connect the RM bridge to google home!

I was going step by step from this " RM Bridge LAN Readme.md " file ... I created the new device handler via the "RM Bridge Switch LAN" and changed the xxx's to the RM bridges local ip ... WITHOUT the http://

I then added a device on smartthings via this device handler, but it doesn't work !!! I was wondering if I'm putting the wrong name/label/device network id or if there is a glitch in the handler code !

I would be grateful if you could kindly help me setting this up ! I've spent hours and hours and wasn't able to get it fixed !

What's the best/easiest way to set the Broadlink with google home !?

Regards,
Milad

**Comment by beckyricha** [comment]
Try this:  I think there have been some changes to smartthings device properties naming.  Seems to be affecting some but not all people, so not sure why.  I have a best way and a quick way to try.  The quick way is to go into your existing file and change where it says "device.displayName" to just "device.name."  Someone else had this issue in the cloud version recently and it worked.  

If that works, a better long term solution is to go to the "temp" branch I just set up, get the BroadLink RM Bridge LAN code from there and paste it into your device handler and add your own ip address and personal info.  Then make the device set up so that the device ID matches the name you used in the RM Bridge (the word before "on" or "off").  You can make the device name the same, or something else if for some reason you want to call it something else in Alexa and SmartThings.  (one reason these may be different - I made some of mine outlet1, outlet2, etc in hte RM Bridge and in thee deviceID.  Then I named it whatever was plugged into it at the time (Christmas tree, for example, won't be forever).  Then I can change its name in the smartthings app to match whatever is plugged in, and just ask Alexa to rediscover devices, without going back to RM Bridge.

If this works, please let me know.  As soon as I can get the readme updated with those instructions I'll merge this into the master branch.

If this doesn't solve it, please make sure the device is linked to the hub. (on your device list in the developer site, the hub should show).  Also please post details of any further issues, such as whether smartthings appears to work and just does nothing, or fails earlier in the process somehow, and whether or not you are using security on the bridge.

**Comment by hapahopa** [comment]
Becky,

Thanks for getting back to me so quick.

I tired both, neither of them work ! deleted the "display" , it didn't help ... created a new device handler using the code on the temp branch , with no luck !

I noticed that I didn't have "on" "off" words on my RM bridge (since I was using it for blinds , and they have up and down)  , just created a new code called : "blind1on" ... and put the device ID as "blind1" that didn't help either !

the device is linked to the hub ... ( when I'm adding the device on the smartthings site, I see the hub and set the location ... 
I also have other stuff on smartthings which works fine ... all the smartthings, android device , broadlink are on the same network ! 
the new device appears on the smart things , but when I click on it (to toggle on/off) it doesn't do anything !
The bridge has no security on it ... I didn't set any username/password if that's what you mean ...
I don't think I have any issue with the bridge tho , cause when I paste the http://192.168.1.74:7474/code/BLNDLivD on the browser, it works ! ...

**Comment by beckyricha** [comment]
OK. If that is not clear on the instructions i will try to fix those. The code must be named with the device name, a space and the word on, and another code the same but off. That device name match the device id if using the new code.
On Jan 7, 2017 7:56 PM, hapahopa <notifications@github.com> wrote:Becky,
Thanks for getting back to me so quick.
I tired both, neither of them work ! deleted the "display" , it didn't help ... created a new device handler using the code on the temp branch , with no luck !
I noticed that I didn't have "on" "off" words on my RM bridge (since I was using it for blinds , and they have up and down)  , just created a new code called : "blind1on" ... and put the device ID as "blind1" that didn't help either !
the device is linked to the hub ... ( when I'm adding the device on the smartthings site, I see the hub and set the location ...
I also have other stuff on smartthings which works fine ... all the smartthings, android device , broadlink are on the same network !
the new device appears on the smart things , but when I click on it (to toggle on/off) it doesn't do anything !
The bridge has no security on it ... I didn't set any username/password if that's what you mean ...
I don't think I have any issue with the bridge tho , cause when I paste the http://192.168.1.74:7474/code/BLNDLivD on the browser, it works ! ...

**Comment by hapahopa** [comment]
GREAT !!! It worked !!! just added the " on" / " off" at the beginning of the code and it worked ! THANK YOU ! I used the code on the temp branch tho for the handler !
