### ISSUE TITLE
change 'on' to 'play' & 'off' to 'pause'

### ISSUE THREAD

**Issue by joemarshalljm** [beckyricha/Broadlink-RM-SmartThings-Alexa#13]
I want to play/pause my Android TV rather than turn 'on' or 'off'

I changed 'on' to play in the code and its not working. What do I need to change?

What I have now:

metadata {
	definition (name: "RM Bridge Pause Cloud", namespace: "smartthings", author: "BeckyR") {
		capability "Switch"
	}

	// tile definitions
	tiles {
		standardTile("switch", "device.switch", width: 2, height: 2, canChangeIcon: true) {
			state "play", label: '${name}', action: "switch.pause", icon: "st.switches.switch.play", backgroundColor: "#79b821"
			state "pause", label: '${name}', action: "switch.play", icon: "st.switches.switch.pause", backgroundColor: "#ffffff"
		}

		main "switch"
		details "switch"
	}
}
 
def play() {
    put('play')
   
   
}

def pause() {
	put('pause')
}
 
private put(toggle) {
    def toReplace = device.name
	def replaced = toReplace.replaceAll(' ', '%20')
def params = [
    uri: "http://xxxxxxx.xxxxxxxxxxxxxxxx:7474/code/$replaced%20$toggle"
]
    httpGet(params) 
}

**Comment by beckyricha** [comment]
This is defined as a switch.  As such it musts have "on" and "off" commands.  I may have ideas but it depends if you are trying to use Alexa or some other smartthings integration.  Unfortunately, using this with Alexa, you are limited to switches, so your best best is a little awkward bu you end up saying something like "turn on play" or "turn on pause" (or whatever suits you, but must start with turn on or turn off).   

If you don't want to use Alexa, you may be able to play with other device types, but you would have to do some research to sort that or maybe someone else here can chime in if they've done it.   In that case you would need to find or create a device type that responds to a capability called "play."  (switches have pre-defined capabilities for on and off, and I also have a device I made for myself that uses a dimmer switch with a level capability to control volume).  If some sort of smartthings device you find can respond to "play" this might work, but again not with Alexa at this time.  To make it work with Alexa you'd have to write a custom skill, but then would have to say somethign like "ask my android to play" which is not much better than "turn on play."

Google Home may open up whole other worlds but I have not played with one yet.  Someone else who has one may also be able to chime in with anything it can do differently.  (if it's good enough, maybe I'll get one).

Hope this helps.

**Comment by joemarshalljm** [comment]
thanks for the reply That a shame, I wanted to be able to say 'turn Shield volume up' but you're saying I'll need to say 'turn shield volume up on' ?

**Comment by beckyricha** [comment]
Actually, volume up is tricky.  It used to work fine, but then Amazon "improved" Alexa's speech recognition, so whenever you talk about volume, it makes Alexa's volume louder.  I would recommend fewer words in your command, and there are also workarounds like turn on louder/softer.   I still use this with my Android because because I don't often use it and default to controlling the TV or computer volume instead (just due to choices in my setup).  

If you can find any program or script that is accessible via http (maybe a tasker thing as I described earlier?)  and can get it working to set the device's volume to a specific numeric level, let me know.  If you have that I can show you how to define the device as a dimmer in smartthings.  Then instead of just on and off, you can use Alexa directly to turn the device on, off, up (I usually say increase the television, because it can mistake up for off),  down, or set it to [numeric level in %].  I do this already on my windows media center but it should work jsut as well on any device once you get something on it for smartthings to send the commands to.

**Comment by joemarshalljm** [comment]
You can use IFTTT to access the RM Bridge Shortcut URL with a channel called Maker. Maybe you can trigger that a number of times. At the moment I have it so I can say 'Trigger volume up' or 'trigger volume down'

**Comment by beckyricha** [comment]
Yeah i have done that too, but have found IFTTT to sometimes lag too much for immediate needs like media control.  It's a great service but can vary in speed like that. If you can get it working well, that is indeed the easiest way. Thanks for adding that option to the conversation.

On Jan 7, 2017 3:23 PM, joemarshalljm <notifications@github.com> wrote:You can use IFTTT to access the RM Bridge Shortcut URL with a channel called Maker. Maybe you can trigger that a number of times. At the moment I have it so I can say 'Trigger volume up' or 'trigger volume down'
