### ISSUE TITLE
Code length limit

### ISSUE THREAD

**Issue by sergejvohrin** [beckyricha/Broadlink-RM-SmartThings-Alexa#5]
Hi,

Thanks a lot for the guide, it is great.
I am facing an issue with one of the remotes. When I record it, and trying to test it from "Manage codes" screen, I am getting the message "Error sending code: data error! length = 908, must be less then 900 bytes". Do you know how this can be fixed? Needless to say, the code does not perform any action.

Would you know how to resolve it?

P.S. For the cloud version you haven't mentioned anywhere how to setup Location that is mandatory field on the new device screen.

Thanks

**Comment by beckyricha** [comment]
Hi. Any issues about code length are either related to the broadlink itself or the RM Bridge software so I would have no way to address that.  It seems odd that any device would send such a long code though. Is it only doing this for some specific device? It may be more beneficial for you to pose question to the bridge app developer for more qualified help.
The location can be anything you want if you are using the cloud. It only matters if using the LAN version because it has to know what hub to use.
Good luck.
Becky
On Oct 23, 2016 6:47 PM, sergejvohrin <notifications@github.com> wrote:Hi,

Thanks a lot for the guide, it is great.
I am facing an issue with one of the remotes. When I record it, and trying to test it from "Manage codes" screen, I am getting the message "Error sending code: data error! length = 908, must be less then 900 bytes". Do you know how this can be fixed? Needless to say, the code does not perform any action.

Would you know how to resolve it?

P.S. For the cloud version you haven't mentioned anywhere how to setup Location that is mandatory field on the new device screen.

Thanks

**Comment by ManfredMaiers** [comment]
I had the same problem with a shutter remote.  It would work with the Broadlink RM app but not with the RM bridge.  I contacted the RM bridge developer, he told me that the lenght limitation is part of the Broadlink API and there is nothing he could do about it.
Manfred



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by Andyycloud** [comment]
hi @sergejvohrin , I've been trying to get this working and hit the same issue. 

One reason for having the data length error is the time you're holding down the button on the remote when it's scanning. I've had this too and if you tap it, it might just work!

**Comment by af950833** [comment]
Hi,
Long code is caused by radio interference.
If you turn off the receiver devices(wall switch, shutter etc) and scan it with olny remote controller, you can avoid this issue.
