### ISSUE TITLE
Button in ST app doesn't reflect state, always shows On

### ISSUE THREAD

**Issue by LandoGemini** [beckyricha/Broadlink-RM-SmartThings-Alexa#8]
Once a RM Bridge LAN/Cloud switch is added to ST and shows up in app it always shows as ON with one exception: if you turn it off it will show as off but will return to on(green) if app si closed or if you move from "My Things" pane.

**Comment by beckyricha** [comment]
Hi. yes, i thought i had this in my explanation of the code but just in case it was not clear I will explain where this stands.  I designed this for Alexa, and made no effort to make the switch states accurate in the st app. This is because these devices can't report their state and can also be changed manually so st has no way of knowing the actual state. Because of this, I didn't spend any time on it. 
However, one of the pull requests did offer a fix for this which i have not yet incorporated. I am not on the site right now but if i recall correctly the user name was itsami, so you might want to look there.  It's been a while but if I recall there were some other changes in that code i didn't think we're universally useful such as sending each code twice (would mess up toggle switch users) so i wanted to give it another look for the best way to incorporate into the master and have not had time yet.    My plan when i get time is to incorporate the switch state piece separately as it's very nice. The work done there to allow a delay and multiple code send is also great but should probably be offered separately to help those who need it.  I recommend checking that out if it would help you. It can be incorporated by simply overwriting the top section of code that was changed, and otherwise the setup works the same as in my instructions.
Thanks.
Becky
On Dec 8, 2016 10:57 AM, LandoGemini <notifications@github.com> wrote:Once a RM Bridge LAN/Cloud switch is added to ST and shows up in app it always shows as ON with one exception: if you turn it off it will show as off but will return to on(green) if app si closed or if you move from "My Things" pane.

**Comment by LandoGemini** [comment]
I understand now. Thank you for the fast response! :) I'll look into the pull request mentioned. 
Thanks and nice work!
Cheers!
Jack

**Comment by itsamti** [comment]
Hi Jack,

I have simplified code. Please try using below

https://raw.githubusercontent.com/itsamti/Broadlink-RM-SmartThings-Alexa/master/Broadlink%20RM%20Bridge%20Switch%20LAN

Thanks,
Amit

**Comment by itsamti** [comment]
Note that if you want to use device name instead of device id, replace below line

From 
def toReplace = device.deviceNetworkId

To
def toReplace = device.displayName

**Comment by LandoGemini** [comment]
Hi Amit,
Thanks for the code! I'll try it out when I get home. 
I've had the hub for about a week and I'm very impressed with the community around it. It's one of its best attributes.

Cheers,
Jack
